# Generated by Django 2.0.2 on 2018-03-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('type', models.IntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=254)),
                ('createTime', models.DateTimeField()),
            ],
        ),
    ]
