# Generated by Django 2.0.2 on 2018-02-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAStream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='orderid',
            field=models.IntegerField(default=-1),
        ),
    ]
