# Generated by Django 2.0.2 on 2018-02-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_vistor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistor',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.User'),
        ),
    ]
